apiVersion: v1
kind: Pod
metadata:
  name: pod-network
spec:
  containers:
  - name: web
    image: chiangfire/springboot-demo:20191122051537
    ports:
    - containerPort: 2019
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
      hostPort: 80
      
  