apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: springboot-web
    image: chiangfire/springboot-demo:20191122051537
    ports:
    - containerPort: 2019
    # 容器里面的挂载目录
    volumeMounts:
    - name: db-secret
      mountPath: /db-secret
      readOnly: true
  # pod里面所有容器的共享信息    
  volumes:
  # 名称
  - name: db-secret
    projected:
      sources:
      # 密钥信息（所使用的secret。注意：这个叫dbpass的secret要提前创建）
      - secret:
          name: dbpass