apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: web
    image: chiangfire/springboot-demo:20191122051537
    # 启动服务的命令（注意：这里可以直接使用下面的环境变量JAVA_OPTS）
    #command: ["/bin/sh", "-c", "java -jar /springboot-demo-0.0.1.jar -DJAVA_OPTS=$(JAVA_OPTS)"]
    ports:
    - containerPort: 2019
    # 配置自定义的环境变量
    env:
      # 自定义环境变量的key
      - name: LOG_LEVEL_CONFIG
        # 环境变量key的值
        valueFrom:
          # 使用configmap里面的某一项配置（就是将configmap里面的某一项配置的值，作为这个环境变量的值）
          configMapKeyRef:
            # configmap的名字（注意：这个configmap要提前创建好）
            name: config-test
            # 要使用configmap的key
            key: LOG_LEVEL
      # 自定义环境变量的key      
      - name: JAVA_OPTS
        valueFrom:
          # 使用configmap里面的某一项配置（就是将configmap里面的某一项配置的值，作为这个环境变量的值）
          configMapKeyRef:
            # configmap的名字（注意：这个configmap要提前创建好）
            name: config-test
            # 要使用configmap的key
            key: JAVA_OPTS      