apiVersion: v1
# 密钥
kind: Secret
metadata:
  # 名称（注意：这个名字可以随便起）
  name: dbpass
# 类型（注意：密钥的类型一般都用这个Opaque，表示不透明的）  
type: Opaque
# 实际的配置信息（注意：实际的信息要通过base64加密后，在填到这里）
# base64加密数据的命令：echo -n jiang|base64；注意：jiang表示要加密的信息
data:
  username: aW1vb2M=
  passwd:  aW1vb2MxMjM=